export const UPDATE_VIDEO = "UPDATE_VIDEO";
export const SET_SEARCH = "SET_SEARCH";
export const SET_PLAYLIST_MODAL = "SET_PLAYLIST_MODAL";
export const SET_PLAYLIST_DATA = "SET_PLAYLIST_DATA";
export const REMOVE_PLAYLIST = "REMOVE_PLAYLIST";
export const SET_ADD_PLAYLIST_MODAL = "SET_ADD_PLAYLIST_MODAL";
export const UPDATE_PLAYLIST = "UPDATE_PLAYLIST";
export const SET_NOTE_MODAL = "SET_NOTE_MODAL";
